import { DQLContext, findProjectRoot } from '@duckcodeailabs/dql-mcp';
import {
  GeminiProvider,
  OllamaProvider,
  OpenAIProvider,
  type AgentMessage,
  type AgentProvider,
} from '@duckcodeailabs/dql-agent';
import type { AgentRunRequest, AgentRunner, AgentTurn, BlockProposal, ProviderId } from '../types.js';

type SimpleProviderId = Extract<ProviderId, 'openai' | 'gemini' | 'ollama'>;

interface ProviderSpec {
  label: string;
  setup: string;
  create(): AgentProvider;
}

const SPECS: Record<SimpleProviderId, ProviderSpec> = {
  openai: {
    label: 'OpenAI',
    setup: 'Set OPENAI_API_KEY. Optional: OPENAI_MODEL and OPENAI_BASE_URL.',
    create: () => new OpenAIProvider({ model: process.env.OPENAI_MODEL }),
  },
  gemini: {
    label: 'Gemini',
    setup: 'Set GEMINI_API_KEY. Optional: GEMINI_MODEL.',
    create: () => new GeminiProvider({ model: process.env.GEMINI_MODEL }),
  },
  ollama: {
    label: 'Ollama',
    setup: 'Start Ollama and set OLLAMA_MODEL if needed. Optional: OLLAMA_BASE_URL.',
    create: () => new OllamaProvider({ model: process.env.OLLAMA_MODEL, baseUrl: process.env.OLLAMA_BASE_URL }),
  },
};

function systemPrompt(ctx: DQLContext, upstreamSql?: string): string {
  const blocks = Object.values(ctx.manifest.blocks);
  const domains = Array.from(new Set(blocks.map((b) => b.domain).filter(Boolean))).sort();
  const blockSummary = Object.entries(ctx.manifest.blocks)
    .slice(0, 40)
    .map(([id, b]) => `- ${id} (${b.domain || 'unknown'}): ${b.description || b.name}`)
    .join('\n');
  const metrics = ctx.semanticLayer.listMetrics().slice(0, 40).map((m) => m.name).join(', ');
  const dimensions = ctx.semanticLayer.listDimensions().slice(0, 40).map((d) => d.name).join(', ');

  return [
    'You are the DQL notebook AI Chat assistant.',
    'Answer with concise analytical guidance grounded in existing DQL blocks and the semantic layer.',
    'When a reusable governed block is appropriate, include a single DQL_BLOCK_PROPOSAL JSON object at the end with name, domain, owner, description, sql, tags, and chartType.',
    'Do not claim a block is certified unless it exists in the project context.',
    '',
    `Project context: ${blocks.length} blocks. Domains: ${domains.join(', ') || '(none)'}.`,
    blockSummary ? `Available blocks:\n${blockSummary}` : '',
    metrics ? `Semantic metrics: ${metrics}` : '',
    dimensions ? `Semantic dimensions: ${dimensions}` : '',
    upstreamSql ? `Current upstream SQL:\n\`\`\`sql\n${upstreamSql}\n\`\`\`` : '',
  ].filter(Boolean).join('\n');
}

function toProviderMessages(req: AgentRunRequest, ctx: DQLContext): AgentMessage[] {
  return [
    { role: 'system', content: systemPrompt(ctx, req.upstream?.sql) },
    ...req.messages.map((m) => ({ role: m.role, content: m.content }) satisfies AgentMessage),
  ];
}

function emitProposalFromText(text: string, emit: (turn: AgentTurn) => void): void {
  const match = text.match(/DQL_BLOCK_PROPOSAL\s*[:=]?\s*(\{[\s\S]*\})\s*$/);
  if (!match) return;
  try {
    const raw = JSON.parse(match[1]) as Partial<BlockProposal>;
    if (!raw.name || !raw.sql) return;
    emit({
      kind: 'proposal',
      proposal: {
        name: String(raw.name),
        domain: String(raw.domain ?? ''),
        owner: String(raw.owner ?? ''),
        description: String(raw.description ?? ''),
        sql: String(raw.sql),
        tags: Array.isArray(raw.tags) ? raw.tags.map(String) : undefined,
        chartType: typeof raw.chartType === 'string' ? raw.chartType : undefined,
      },
      governance: { certified: false, errors: [], warnings: ['Generated by a non-tool provider; review before saving.'] },
    });
  } catch {
    // Ignore malformed proposal text. The visible assistant response still streams as text.
  }
}

export function createDqlAgentProviderRunner(id: SimpleProviderId): AgentRunner {
  return {
    async run(req, emit, signal) {
      const spec = SPECS[id];
      const provider = spec.create();
      const available = await provider.available().catch(() => false);
      if (!available) {
        emit({ kind: 'error', message: `${spec.label} is not configured or reachable. ${spec.setup}` });
        return;
      }

      try {
        emit({ kind: 'thinking', text: `Using ${spec.label} for this turn.` });
        const ctx = new DQLContext({ projectRoot: findProjectRoot(req.projectRoot) });
        const text = await provider.generate(toProviderMessages(req, ctx), { signal, maxTokens: 2048 });
        emit({ kind: 'text', text });
        emitProposalFromText(text, emit);
        emit({ kind: 'done', stopReason: 'stop' });
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        emit({ kind: 'error', message: `${spec.label} failed: ${message}. ${spec.setup}` });
      }
    },
  };
}
