// Manifest — DQL project compilation artifact

export {
  buildManifest,
  collectInputFiles,
  loadProjectConfig,
  resolveDataLexManifestPath,
  resolveDbtManifestPath,
  type ManifestBuildOptions,
  type DbtImportFilters,
} from './builder.js';

export { detectOutputDrift } from './output-drift.js';
export {
  loadDbtFirstModeling,
  siblingDbtArtifact,
  relationshipValidationProofFingerprint,
  type DbtFirstModelingLoadResult,
} from './dbt-first-modeling.js';
export {
  previewModelingChange,
  applyModelingChange,
  previewDbtSourcePatch,
  applyDbtSourcePatch,
  loadDbtNodeAuthoringDetail,
  resetDbtArtifactReadCount,
  dbtArtifactReadCount,
  type DomainPackageAuthoringInput,
  type ModelAreaAuthoringInput,
  type EntityBindingAuthoringInput,
  type RelationshipAuthoringInput,
  type ContractAuthoringInput,
  type DomainExportAuthoringInput,
  type DomainImportAuthoringInput,
  type ModelingAuthoringChange,
  type ModelingSourcePatch,
  type ModelingChangePreview,
  type DbtNodeAuthoringDetail,
  type DbtSourceAuthoringInput,
  type DbtSourcePatchPreview,
} from './dbt-first-authoring.js';
export {
  planDataLexMigration,
  applyDataLexMigration,
  type DataLexMigrationInput,
  type DataLexMigrationFile,
  type DataLexMigrationLoss,
  type DataLexMigrationAmbiguity,
  type DataLexMigrationReport,
  type DataLexMigrationPlan,
} from './datalex-migration.js';
export {
  writeDomainDeclaration,
  deleteDomainDeclaration,
  renderDomainDeclaration,
  resolveDomainDeclPath,
  domainFolderSlug,
  type DomainInput,
  type WrittenDomain,
} from './domain-writer.js';
export {
  loadDomainPackageRegistry,
  type DomainPackageRecord,
  type DomainPackageRegistryResult,
} from './domain-package-registry.js';
export {
  discoverDbtDomains,
  type DiscoverDbtDomainsOptions,
  type DomainDiscoveryEvidenceKind,
  type DomainDiscoveryEvidence,
  type DomainMembershipProposal,
  type DomainProposal,
  type UnassignedDbtModel,
  type RelationshipDraftCandidate,
  type SkillDraftCandidate,
  type DomainDiscoveryReport,
} from './domain-discovery.js';
export {
  ProjectSnapshotService,
  ProjectSnapshotMismatchError,
  type ProjectSnapshot,
} from './project-snapshot.js';
export {
  buildManifestKnowledgeGraph,
  compactManifestKnowledgeGraph,
  KNOWLEDGE_INDEX_SCHEMA_VERSION,
  type BuildManifestKnowledgeGraphInput,
} from './knowledge-graph.js';
export {
  loadManifestKnowledgeSkills,
  manifestKnowledgeSkillInputFiles,
  type ManifestKnowledgeSkillDescriptor,
  type ManifestKnowledgeSkillLoadResult,
} from './knowledge-skills.js';
export {
  loadDbtRunState,
  applyBlockDataState,
  worseDataState,
  type DbtRunStateIndex,
} from './dbt-freshness.js';

export type {
  DQLManifest,
  ManifestBlock,
  ManifestDomain,
  ManifestTerm,
  ManifestBusinessView,
  ManifestNotebook,
  ManifestNotebookCell,
  ManifestMetric,
  ManifestDimension,
  ManifestSource,
  ManifestLineage,
  ManifestLineageNode,
  ManifestLineageEdge,
  ManifestDbtImport,
  ManifestDbtProvenance,
  ManifestDbtNodeProvenance,
  ManifestMetricFlowProvenance,
  ManifestDbtFirstModeling,
  ManifestDomainPackage,
  ManifestModelArea,
  ManifestModelEntity,
  ManifestModelRelationship,
  ManifestRelationshipValidationEvidence,
  ManifestRelationshipCardinality,
  ManifestFanoutPolicy,
  ManifestRelationshipOptionality,
  ManifestRelationshipJoinType,
  ManifestRelationshipAggregationPolicy,
  ManifestRelationshipTemporalPolicy,
  ManifestModelContract,
  ManifestDomainExport,
  ManifestDomainImport,
  ManifestConformanceDeclaration,
  ManifestModelRule,
  ManifestDomainRelationshipLineage,
  ManifestKnowledgeGraph,
  ManifestKnowledgeObject,
  ManifestKnowledgeObjectRef,
  ManifestKnowledgeShard,
  ManifestKnowledgeObjectKind,
  ManifestKnowledgeEdge,
  ManifestKnowledgeEdgeKind,
  ManifestKnowledgeRouteState,
  ManifestKnowledgeSource,
  ManifestDomainCapsule,
  ManifestCrossDomainRoute,
  ManifestDiagnostic,
  ManifestConflictDetail,
  ManifestConflictSide,
  ManifestDriftDetail,
  ManifestApp,
  ManifestDashboard,
  DbtDataState,
  DbtRunState,
} from './types.js';
