/**
 * DQL Manifest — the compiled project artifact.
 *
 * Similar to dbt's manifest.json, this is the single source of truth
 * for a DQL project's structure, dependencies, and lineage.
 * Generated by `dql compile`, consumed by `dql lineage`, notebook panel,
 * and external tools (DataHub, Atlan, etc.).
 */

// ---- Top-level manifest ----

export interface DQLManifest {
  /** Manifest schema version */
  manifestVersion: 1 | 2;
  /** DQL CLI version that generated this manifest */
  dqlVersion: string;
  /** ISO 8601 timestamp */
  generatedAt: string;
  /** Project name from dql.config.json */
  project: string;
  /** Absolute path to project root */
  projectRoot: string;

  /** All blocks discovered in the project */
  blocks: Record<string, ManifestBlock>;
  /** All notebook SQL/DQL cells */
  notebooks: Record<string, ManifestNotebook>;
  /** Semantic layer definitions */
  metrics: Record<string, ManifestMetric>;
  dimensions: Record<string, ManifestDimension>;
  /** External source tables (from SQL extraction + dbt import) */
  sources: Record<string, ManifestSource>;

  /** Pre-computed lineage graph */
  lineage: ManifestLineage;

  /** dbt manifest import metadata (if --dbt-manifest was used) */
  dbtImport?: ManifestDbtImport;

  /**
   * Non-fatal problems encountered during the build — files that failed to
   * parse, references that could not be resolved, etc. Empty array on a
   * clean build. `dql compile` prints these as warnings; `dql doctor`
   * surfaces them as diagnostics.
   */
  diagnostics?: ManifestDiagnostic[];
}

export interface ManifestDiagnostic {
  /** 'parse' | 'resolve' | 'dbt' | 'semantic' | 'config' */
  kind: string;
  /** Relative path to the offending file, if any */
  filePath?: string;
  severity: 'error' | 'warning';
  message: string;
}

// ---- Blocks ----

export interface ManifestBlock {
  name: string;
  /** Relative path from project root */
  filePath: string;
  domain?: string;
  owner?: string;
  status?: string;
  blockType?: string;
  /** Raw SQL from the block's query */
  sql: string;
  /** Tables extracted from SQL (before normalization) */
  rawTableRefs: string[];
  /** Normalized table dependencies */
  tableDependencies: string[];
  /** Block dependencies via ref() */
  refDependencies: string[];
  /** @metric() references in SQL */
  metricRefs?: string[];
  /** @dim() references in SQL */
  dimensionRefs?: string[];
  /** All upstream dependencies (tables + refs + semantic refs combined) */
  allDependencies: string[];
  /** Visualization chart type */
  chartType?: string;
  /** Metric reference for semantic blocks */
  metricRef?: string;
  /** Test assertions defined in the block */
  tests: string[];
  /** Tags from block metadata */
  tags?: string[];
  description?: string;
}

// ---- Notebooks ----

export interface ManifestNotebook {
  /** Notebook title */
  title: string;
  /** Relative path from project root */
  filePath: string;
  /** SQL/DQL cells with lineage-relevant content */
  cells: ManifestNotebookCell[];
}

export interface ManifestNotebookCell {
  id: string;
  type: 'sql' | 'dql';
  title?: string;
  /** Raw SQL/DQL source */
  source: string;
  /** Tables extracted from SQL */
  tableDependencies: string[];
  /** ref() dependencies */
  refDependencies: string[];
  /** Block name (for DQL cells that declare a block) */
  blockName?: string;
  /** Chart config (if a chart cell references this cell) */
  chartType?: string;
  /** Path of a `.dql` block file this cell is bound to (Track 5 block-first cells) */
  bindingPath?: string;
}

// ---- Semantic Layer ----

export interface ManifestMetric {
  name: string;
  type: string;
  table: string;
  domain?: string;
  description?: string;
  sql?: string;
  /** Relative path to the YAML file */
  filePath?: string;
}

export interface ManifestDimension {
  name: string;
  table: string;
  type?: string;
  description?: string;
  filePath?: string;
}

// ---- Sources ----

export interface ManifestSource {
  /** Normalized table name */
  name: string;
  /** Raw reference as found in SQL (e.g., "read_csv_auto('./data/file.csv')") */
  rawRef?: string;
  /** Origin: 'sql' = extracted from SQL, 'semantic' = from YAML, 'dbt' = from dbt manifest */
  origin: 'sql' | 'semantic' | 'dbt';
  /** Which blocks/cells reference this source */
  referencedBy: string[];
  /** dbt model metadata (if imported from dbt manifest) */
  dbtModel?: {
    uniqueId: string;
    database?: string;
    schema?: string;
    materializedAs?: string;
    description?: string;
    columns?: Record<string, { name: string; description?: string; type?: string }>;
  };
}

// ---- Lineage ----

export interface ManifestLineage {
  nodes: ManifestLineageNode[];
  edges: ManifestLineageEdge[];
  domains: string[];
  crossDomainFlows: Array<{ from: string; to: string; edgeCount: number }>;
  domainTrust: Record<string, { total: number; certified: number; score: number }>;
}

export interface ManifestLineageNode {
  id: string;
  type: string;
  name: string;
  layer?: string;
  domain?: string;
  owner?: string;
  status?: string;
  filePath?: string;
  columns?: Array<{ name: string; type?: string; description?: string }>;
  metadata?: Record<string, unknown>;
}

export interface ManifestLineageEdge {
  source: string;
  target: string;
  type: string;
  sourceDomain?: string;
  targetDomain?: string;
}

// ---- dbt Import ----

export interface ManifestDbtImport {
  /** Path to the dbt manifest.json that was imported */
  manifestPath: string;
  /** dbt project name */
  projectName?: string;
  /** Number of models imported (in the selected subgraph) */
  modelsImported: number;
  /** Number of sources imported (in the selected subgraph) */
  sourcesImported: number;
  /** Total models in the dbt manifest (before selective filtering) */
  totalDbtModels?: number;
  /** Whether selective import was applied (only relevant upstream subgraph imported) */
  selective?: boolean;
  /** Max upstream hops used for selective import (undefined = unlimited) */
  maxHops?: number;
  /** Timestamp of import */
  importedAt: string;
  /** Imported dbt DAG metadata */
  dbtDag?: {
    models: Array<{
      uniqueId: string;
      name: string;
      type: 'model' | 'source';
      dependsOn: string[];
      columns?: Array<{ name: string; type?: string; description?: string }>;
      schema?: string;
      database?: string;
      materialized?: string;
      description?: string;
    }>;
    edges: Array<{ source: string; target: string }>;
  };
}
