/**
 * DQL Manifest — the compiled project artifact.
 *
 * Similar to dbt's manifest.json, this is the single source of truth
 * for a DQL project's structure, dependencies, and lineage.
 * Generated by `dql compile`, consumed by `dql lineage`, notebook panel,
 * and external tools (DataHub, Atlan, etc.).
 */

// ---- Top-level manifest ----

export interface DQLManifest {
  /** Manifest schema version */
  manifestVersion: 1 | 2;
  /** DQL CLI version that generated this manifest */
  dqlVersion: string;
  /** ISO 8601 timestamp */
  generatedAt: string;
  /** Project name from dql.config.json */
  project: string;
  /** Absolute path to project root */
  projectRoot: string;

  /** First-class business domains discovered in the project */
  domains?: Record<string, ManifestDomain>;
  /** All blocks discovered in the project */
  blocks: Record<string, ManifestBlock>;
  /** Business composition views discovered in the project */
  businessViews: Record<string, ManifestBusinessView>;
  /** Business glossary terms discovered in the project */
  terms: Record<string, ManifestTerm>;
  /** All notebook SQL/DQL cells */
  notebooks: Record<string, ManifestNotebook>;
  /** Semantic layer definitions */
  metrics: Record<string, ManifestMetric>;
  dimensions: Record<string, ManifestDimension>;
  /** External source tables (from SQL extraction + dbt import) */
  sources: Record<string, ManifestSource>;
  /**
   * Consumption-layer artifacts: Apps bundle dashboards/notebooks for a domain
   * or team with members, roles, policies, RLS bindings, and schedules.
   * Empty record when no `apps/` directory exists.
   */
  apps?: Record<string, ManifestApp>;
  /**
   * First-class dashboards (`.dqld`) discovered under `apps/<id>/dashboards/`.
   * Distinct from notebook-as-dashboard (which still ships under `notebooks`).
   */
  dashboards?: Record<string, ManifestDashboard>;

  /** Pre-computed lineage graph */
  lineage: ManifestLineage;

  /** dbt manifest import metadata (if --dbt-manifest was used) */
  dbtImport?: ManifestDbtImport;

  /**
   * Non-fatal problems encountered during the build — files that failed to
   * parse, references that could not be resolved, etc. Empty array on a
   * clean build. `dql compile` prints these as warnings; `dql doctor`
   * surfaces them as diagnostics.
   */
  diagnostics?: ManifestDiagnostic[];
}

export interface ManifestDiagnostic {
  /**
   * 'parse' | 'resolve' | 'dbt' | 'semantic' | 'config' | 'conflict' | 'drift'
   *
   * `conflict` (additive) flags two certified governance artifacts — two terms
   * or two certified blocks — that target the same concept/identifier/grain but
   * disagree on their definition, business rules, or SQL semantics. A governed
   * system must surface this rather than silently pick one; see
   * `detectTrustConflicts` in semantic/conflicts and the agent's `conflict`
   * route. Conflict diagnostics carry an optional `conflict` payload so
   * consumers can route on the two sides without re-parsing the message.
   *
   * `drift` (additive, always `severity: 'warning'`) flags output-contract
   * drift in the intentionally freeform `ref()` composition model: a parent
   * block P references a column on child block C via `ref()`, but that column
   * is no longer part of C's current output schema (renamed or removed).
   * DQL does not restrict composition, so this is surfaced as a *warning* —
   * it never fails the build. Drift diagnostics carry an optional `drift`
   * payload naming P, C, and the missing column. See `detectOutputDrift` in
   * manifest/output-drift and `outputContract` on `ManifestBlock`.
   */
  kind: string;
  /** Relative path to the offending file, if any */
  filePath?: string;
  severity: 'error' | 'warning';
  message: string;
  /**
   * Present only on `kind: 'conflict'` diagnostics. Names the conflicting
   * governance pair so route-time consumers can present both sides + owners.
   */
  conflict?: ManifestConflictDetail;
  /**
   * Present only on `kind: 'drift'` diagnostics. Names the parent block, the
   * child block, and the drifted (missing/renamed) column so consumers can
   * route without re-parsing the message.
   */
  drift?: ManifestDriftDetail;
}

/**
 * Structured detail for a `kind: 'drift'` diagnostic. The parent block
 * references `column` on the child block via `ref()`, but `column` is no
 * longer present in the child's `outputContract`. `availableColumns` lists the
 * child's current output columns so a consumer can suggest the likely rename.
 */
export interface ManifestDriftDetail {
  /** The block that does the `ref()` and references the drifted column. */
  parentBlock: string;
  /** The referenced (child) block whose output schema changed. */
  childBlock: string;
  /** The referenced column that is no longer in the child's output. */
  column: string;
  /** The child's current output column names, for rename suggestions. */
  availableColumns: string[];
}

/**
 * Structured detail for a `kind: 'conflict'` diagnostic: the two governed
 * artifacts that claim the same concept but disagree, plus the disambiguation
 * prompt a human (or the agent's `conflict` route) should surface.
 */
export interface ManifestConflictDetail {
  /** The kind of governed object in conflict. */
  objectType: 'term' | 'block';
  /** The shared concept key (identifier + grain) that both sides claim. */
  concept: string;
  /** Why the two sides are considered divergent. */
  reason: string;
  /** A ready-to-show disambiguation prompt naming both sides. */
  prompt: string;
  /** The two (or more) conflicting sides, each with its owner + definition. */
  sides: ManifestConflictSide[];
}

export interface ManifestConflictSide {
  name: string;
  filePath?: string;
  owner?: string;
  domain?: string;
  /** The definition/description text that diverges. */
  definition?: string;
  /** The business rules that diverge. */
  businessRules?: string[];
}

// ---- Blocks ----

export interface ManifestBlock {
  name: string;
  /** Relative path from project root */
  filePath: string;
  domain?: string;
  owner?: string;
  status?: string;
  blockType?: string;
  /** Raw SQL from the block's query */
  sql: string;
  /** Tables extracted from SQL (before normalization) */
  rawTableRefs: string[];
  /** Normalized table dependencies */
  tableDependencies: string[];
  /** Block dependencies via ref() */
  refDependencies: string[];
  /** @metric() references in SQL */
  metricRefs?: string[];
  /** @dim() references in SQL */
  dimensionRefs?: string[];
  /** Semantic dimension references declared by a semantic block */
  dimensionsRef?: string[];
  /** All upstream dependencies (tables + refs + semantic refs combined) */
  allDependencies: string[];
  /** Visualization chart type */
  chartType?: string;
  /** Consumer display hints derived from block visualization metadata. Apps/notebooks may override these. */
  displayHints?: ManifestBlockDisplayHints;
  /** Metric reference for semantic blocks */
  metricRef?: string;
  /** Metric references for semantic blocks */
  metricsRef?: string[];
  /** Test assertions defined in the block */
  tests: string[];
  /** Tags from block metadata */
  tags?: string[];
  description?: string;
  /** Business term names declared by this block and resolved in the manifest. */
  termRefs?: string[];
  /** Official DQL block pattern, such as entity_profile, ranking, trend, or bridge. */
  pattern?: string;
  /** Enterprise reusable-widget grain, for example customer_id or month. */
  grain?: string;
  /** Business entities represented by the row grain or output. */
  entities?: string[];
  /** Declared output field names reviewers should expect. */
  declaredOutputs?: string[];
  /** Business dimensions reviewers can reuse for grouping or app filters. */
  dimensions?: string[];
  /** Filters this block is designed to support safely. */
  allowedFilters?: string[];
  /** Parameter reuse policy per block parameter. */
  parameterPolicy?: ManifestBlockParameterPolicy[];
  /** Business/app filter to physical column or expression bindings. */
  filterBindings?: ManifestBlockFilterBinding[];
  /** Business/source systems represented by this block. */
  sourceSystems?: string[];
  /** Block names this block is intended to replace or supersede. */
  replacementFor?: string[];
  /** Business term names declared by this block that were not found during compile. */
  unresolvedTermRefs?: string[];
  /**
   * v1.2 Track G — agent-facing metadata surfaced to MCP tools.
   * Kept optional and additive; adoption is organic (has-llm-context is a warning rule).
   */
  llmContext?: string;
  examples?: Array<{ question: string; sql?: string }>;
  invariants?: string[];
  businessOutcome?: string;
  businessOwner?: string;
  decisionUse?: string;
  reviewCadence?: string;
  businessRules?: string[];
  caveats?: string[];
  /**
   * v1.6 — DataLex contract reference (`<domain>.<Entity>.<contract_name>`
   * with optional `@<version>` suffix). When present, the compiler
   * resolved it against the project's DataLex manifest. Unresolved or
   * malformed references surface as analyzer diagnostics; see
   * contracts/registry.ts.
   */
  datalexContract?: string;
  /** Tier-2 generated draft metadata, present for review-required generated proposals. */
  draftMetadata?: {
    sourceQuestion?: string;
    sourceBlock?: string;
    followupKind?: string;
    requestedFilters?: string[];
    requestedDimensions?: string[];
    contextPackId?: string;
    routeIntent?: string;
    askedTimes?: number;
    validationWarnings?: string[];
    proposedContractId?: string;
    proposedDomain?: string;
    proposedEntity?: string;
    upstreamRefs?: string[];
    firstAsked?: string;
    lastAsked?: string;
  };
  /**
   * v1.6 — Column-level lineage for the block's SELECT output. Each entry
   * names an output column and the source table.column refs it depends on
   * (extracted via node-sql-parser). Unresolved entries (star expansion,
   * complex expressions, etc.) are flagged so consumers can fall back to
   * table-level lineage. See lineage/column-lineage.ts.
   */
  outputs?: Array<{
    name: string;
    isAggregate?: boolean;
    aggregateFn?: string;
    sources: Array<{ table: string; column: string }>;
    unresolved?: boolean;
  }>;
  /**
   * Typed output contract — the columns a parent that `ref()`s this block can
   * rely on. Additive and distinct from `outputs` (which is column-lineage
   * shaped); do NOT conflate the two. Populated from `declaredOutputs` (the
   * reviewer-declared field names) merged with column-lineage extraction. Each
   * entry names a column and, when known, its `type` and reuse `role`
   * (e.g. 'metric', 'dimension', 'grain'). Consumers and existing manifests
   * that predate this field stay valid — it is always optional.
   *
   * Drives compile-time output-contract drift detection: when this block's
   * output schema changes, a parent referencing a now-missing column produces
   * a `kind: 'drift'`, `severity: 'warning'` diagnostic (never fails the
   * build). See `detectOutputDrift` in manifest/output-drift.
   */
  outputContract?: Array<{ name: string; type?: string; role?: string }>;
}

export interface ManifestBlockDisplayHints {
  defaultVisualization?: string;
  allowedVisualizations?: string[];
  fieldHints?: Record<string, string>;
  source: 'block_visualization' | 'derived' | 'ai_import';
}

export interface ManifestBlockParameterPolicy {
  name: string;
  policy: string;
}

export interface ManifestBlockFilterBinding {
  filter: string;
  binding: string;
}

// ---- Business Domains ----

export interface ManifestDomain {
  name: string;
  /** Relative path from project root */
  filePath: string;
  owner?: string;
  businessOwner?: string;
  boundedContext?: string;
  sourceSystems?: string[];
  primaryTerms?: string[];
  reviewCadence?: string;
  tags?: string[];
  businessOutcome?: string;
  description?: string;
}

// ---- Business Terms ----

export interface ManifestTerm {
  name: string;
  /** Relative path from project root */
  filePath: string;
  domain?: string;
  owner?: string;
  status?: string;
  termType?: string;
  tags?: string[];
  description?: string;
  identifiers?: string[];
  synonyms?: string[];
  businessOutcome?: string;
  businessOwner?: string;
  decisionUse?: string;
  reviewCadence?: string;
  businessRules?: string[];
  caveats?: string[];
}

// ---- Business Views ----

export interface ManifestBusinessView {
  name: string;
  /** Relative path from project root */
  filePath: string;
  domain?: string;
  owner?: string;
  status?: string;
  tags?: string[];
  description?: string;
  businessOutcome?: string;
  businessOwner?: string;
  decisionUse?: string;
  reviewCadence?: string;
  businessRules?: string[];
  caveats?: string[];
  /** Block names included by this business view and resolved in the manifest. */
  blockRefs: string[];
  /** Business view names included by this business view and resolved in the manifest. */
  businessViewRefs: string[];
  /** All business term refs represented by this view, including terms inherited from included blocks/views. */
  termRefs: string[];
  /** Business term names directly declared by this business view and resolved in the manifest. */
  declaredTermRefs: string[];
  /** Business term names inherited from included blocks and business views. */
  inheritedTermRefs: string[];
  /** Directly declared business term names that were not found during compile. */
  unresolvedTermRefs: string[];
  /** Referenced block names that were not found during compile. */
  unresolvedBlockRefs: string[];
  /** Referenced business view names that were not found during compile. */
  unresolvedBusinessViewRefs: string[];
}

// ---- Notebooks ----

export interface ManifestNotebook {
  /** Notebook title */
  title: string;
  /** Relative path from project root */
  filePath: string;
  /** SQL/DQL cells with lineage-relevant content */
  cells: ManifestNotebookCell[];
}

export interface ManifestNotebookCell {
  id: string;
  type: 'sql' | 'dql';
  title?: string;
  /** Raw SQL/DQL source */
  source: string;
  /** Tables extracted from SQL */
  tableDependencies: string[];
  /** ref() dependencies */
  refDependencies: string[];
  /** Block name (for DQL cells that declare a block) */
  blockName?: string;
  /** Chart config (if a chart cell references this cell) */
  chartType?: string;
  /** Path of a `.dql` block file this cell is bound to (Track 5 block-first cells) */
  bindingPath?: string;
}

// ---- Semantic Layer ----

export interface ManifestMetric {
  name: string;
  type: string;
  table: string;
  domain?: string;
  description?: string;
  sql?: string;
  /** Relative path to the YAML file */
  filePath?: string;
}

export interface ManifestDimension {
  name: string;
  table: string;
  type?: string;
  description?: string;
  filePath?: string;
}

// ---- Sources ----

export interface ManifestSource {
  /** Normalized table name */
  name: string;
  /** Raw reference as found in SQL (e.g., "read_csv_auto('./data/file.csv')") */
  rawRef?: string;
  /** Origin: 'sql' = extracted from SQL, 'semantic' = from YAML, 'dbt' = from dbt manifest */
  origin: 'sql' | 'semantic' | 'dbt';
  /** Which blocks/cells reference this source */
  referencedBy: string[];
  /** dbt model metadata (if imported from dbt manifest) */
  dbtModel?: {
    uniqueId: string;
    database?: string;
    schema?: string;
    materializedAs?: string;
    description?: string;
    columns?: Record<string, { name: string; description?: string; type?: string }>;
  };
}

// ---- Lineage ----

export interface ManifestLineage {
  nodes: ManifestLineageNode[];
  edges: ManifestLineageEdge[];
  domains: string[];
  crossDomainFlows: Array<{ from: string; to: string; edgeCount: number }>;
  domainTrust: Record<string, { total: number; certified: number; score: number }>;
}

export interface ManifestLineageNode {
  id: string;
  type: string;
  name: string;
  layer?: string;
  domain?: string;
  owner?: string;
  status?: string;
  filePath?: string;
  columns?: Array<{ name: string; type?: string; description?: string }>;
  metadata?: Record<string, unknown>;
}

export interface ManifestLineageEdge {
  source: string;
  target: string;
  type: string;
  sourceDomain?: string;
  targetDomain?: string;
}

// ---- Apps & Dashboards (consumption layer) ----

export interface ManifestApp {
  id: string;
  name: string;
  description?: string;
  businessOutcome?: string;
  businessOwner?: string;
  decisionUse?: string;
  reviewCadence?: string;
  businessRules?: string[];
  caveats?: string[];
  domain: string;
  subdomain?: string;
  groups?: string[];
  audience?: string;
  visibility: 'shared' | 'private' | 'template';
  lifecycle: 'draft' | 'review' | 'certified' | 'deprecated';
  owners: string[];
  tags: string[];
  /** Folder path relative to project root (e.g. "apps/growth-cxo"). */
  filePath: string;
  /** Member directory; empty for solo Apps. */
  members: Array<{
    userId: string;
    displayName?: string;
    roles: string[];
    attributes?: Record<string, string | number | boolean>;
  }>;
  /** Roles declared by the App. */
  roles: Array<{ id: string; displayName?: string; description?: string }>;
  /** Access policies; reuses dql-governance shape. */
  policies: Array<{
    id: string;
    description?: string;
    domain: string;
    minClassification: 'public' | 'internal' | 'confidential' | 'restricted';
    allowedRoles: string[];
    allowedUsers?: string[];
    accessLevel: 'read' | 'write' | 'execute' | 'admin';
    enabled: boolean;
  }>;
  /** RLS template variable bindings (role → variable ← member attribute). */
  rlsBindings: Array<{ role: string; variable: string; from: string }>;
  /** Cron-driven dashboard deliveries (Slack, email, webhook). */
  schedules: Array<{
    id: string;
    cron: string;
    dashboard: string;
    deliver: Array<
      | { kind: 'slack'; channel: string }
      | { kind: 'email'; to: string[] }
      | { kind: 'webhook'; url: string }
    >;
    description?: string;
    enabled: boolean;
  }>;
  /** Dashboard ids declared inside this App. */
  dashboards: string[];
  /** Notebook refs explicitly attached to this App. */
  notebooks: Array<{
    path: string;
    title?: string;
    role: 'source' | 'analysis' | 'supporting';
    visibility: 'shared' | 'private' | 'template';
  }>;
  /** Optional homepage shown when stakeholders open the App. */
  homepage?:
    | { type: 'dashboard'; id: string }
    | { type: 'notebook'; path: string };
  /** Non-fatal load problems for this App, if any. */
  diagnostics?: ManifestDiagnostic[];
}

export interface ManifestDashboard {
  id: string;
  /** Owning App id. */
  appId: string;
  /** Namespaced dashboard id used as the manifest key, e.g. "growth-cxo/overview". */
  qualifiedId: string;
  title: string;
  description?: string;
  businessOutcome?: string;
  businessOwner?: string;
  decisionUse?: string;
  reviewCadence?: string;
  businessRules?: string[];
  caveats?: string[];
  domain?: string;
  subdomain?: string;
  groups?: string[];
  audience?: string;
  visibility?: 'shared' | 'private' | 'template';
  lifecycle?: 'draft' | 'review' | 'certified' | 'deprecated';
  tags: string[];
  /** Path relative to project root (e.g. "apps/growth-cxo/dashboards/weekly-overview.dqld"). */
  filePath: string;
  /** Block names referenced by id (already resolved against the manifest's blocks map). */
  blockIds: string[];
  /** Block names referenced by file path that resolved to a known block. */
  blockPathRefs: string[];
  /** Block names that could not be resolved — surfaced as diagnostics. */
  unresolvedRefs: string[];
  /** Param ids declared on the dashboard. */
  params: string[];
  /** Filter ids declared on the dashboard. */
  filters: string[];
  /** Layout summary; full grid lives on disk. */
  layout: { kind: 'grid'; cols: number; rowHeight: number; itemCount: number };
}

// ---- dbt Import ----

export interface ManifestDbtImport {
  /** Path to the dbt manifest.json that was imported */
  manifestPath: string;
  /** dbt project name */
  projectName?: string;
  /** Number of models imported (in the selected subgraph) */
  modelsImported: number;
  /** Number of sources imported (in the selected subgraph) */
  sourcesImported: number;
  /** Total models in the dbt manifest (before selective filtering) */
  totalDbtModels?: number;
  /** Whether selective import was applied (only relevant upstream subgraph imported) */
  selective?: boolean;
  /** Max upstream hops used for selective import (undefined = unlimited) */
  maxHops?: number;
  /** Timestamp of import */
  importedAt: string;
  /** Imported dbt DAG metadata */
  dbtDag?: {
    models: Array<{
      uniqueId: string;
      name: string;
      type: 'model' | 'source';
      dependsOn: string[];
      columns?: Array<{ name: string; type?: string; description?: string }>;
      schema?: string;
      database?: string;
      materialized?: string;
      description?: string;
    }>;
    edges: Array<{ source: string; target: string }>;
  };
}
